---
- name: Install Required Packages
  apt:
    name: "{{ mariadb_required_packages }}"

- name: Add MariaDB Repository Key
  apt_key:
    keyserver: "{{mariadb_keyserver}}"
    id: "{{ mariadb_apt_key_id }}"

- name: Add MariaDB APT Repository
  apt_repository:
    repo: deb {{mariadb_apt_repo_url}}{{ mariadb_version}}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    state: present
    filename: mariadb

- name: Install MariaDB Server
  package: name=mariadb-server state=present
  notify: Restart MariaDB

- name: Install Additional Packages
  apt:
    name: "{{ mariadb_additional_packages }}"
